### ISSUE TITLE
Error NodeRED and Docker

### ISSUE THREAD

**Issue by aleksandrdobrynin** [CABrouwers/telnet-engine#3]
Hey.
Installed a node in NodeRED, which is deployed in Docker. I get an error when trying to start. In the node manager, I get the following:
Error: Cannot find module 'C: /Users/Charles-Andre.HOME/source/repos/telnet-engine/index.js' (line: 4)
Error: Cannot find module 'C: /Users/Charles-Andre.HOME/source/repos/telnet-engine/index.js' (line: 4)

**Comment by CABrouwers** [comment]
Yes, but the issue was in the module "node-red-contrib-telnet" and was just corrected.  As soon the node-red system picks up the new version I uploaded on npm. i will re-test it.
